import type { Metadata } from "next";
import { siteConfig } from "@/config/site";

interface BuildMetadataInput {
  title: string;
  description: string;
  /** Path relative to the site root, e.g. "/", "/blog", "/blog/some-slug". */
  path: string;
  images?: string[];
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
}

/** Absolute, www-canonical URL for a given site-relative path. */
export function absoluteUrl(path: string): string {
  if (path === "/") return `${siteConfig.url}/`;
  return `${siteConfig.url}${path}`;
}

/**
 * Default Open Graph/Twitter image, generated by app/opengraph-image.tsx.
 * Used as a fallback wherever a route has no image of its own (e.g. a blog
 * post with no WordPress featured image), since Next.js does not fall back
 * to a parent segment's file-convention image once a route sets its own
 * openGraph object.
 */
export const DEFAULT_OG_IMAGE = absoluteUrl("/opengraph-image");

/**
 * Builds a self-contained Metadata object (title, description, canonical,
 * Open Graph, Twitter) for a single route. Each route sets its own full
 * Open Graph/Twitter object rather than relying on layout inheritance,
 * since Next.js does not deep-merge these nested fields across segments.
 */
export function buildMetadata({
  title,
  description,
  path,
  images,
  type = "website",
  publishedTime,
  modifiedTime,
}: BuildMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const resolvedImages = images && images.length > 0 ? images : [DEFAULT_OG_IMAGE];

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: siteConfig.name,
      locale: "ko_KR",
      type,
      images: resolvedImages,
      ...(publishedTime ? { publishedTime } : {}),
      ...(modifiedTime ? { modifiedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: resolvedImages,
    },
  };
}
